CREATE TABLE salt (
    id CHAR(36) NOT NULL PRIMARY KEY,
    salt VARCHAR(255) NOT NULL,
    expired TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE password (
    id CHAR(36) NOT NULL PRIMARY KEY,
    password_hash VARCHAR(255) NOT NULL,
    id_salt CHAR(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_salt) REFERENCES salt(id) ON DELETE CASCADE
);

CREATE TABLE users (
    id CHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    id_salt CHAR(36) NOT NULL,
    id_church CHAR(36) NOT NULL,
    id_ministry CHAR(36) NOT NULL,  
    id_instrument CHAR(36) NOT NULL,
    id_status CHAR(36) NOT NULL,    
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_salt) REFERENCES salt(id) ON DELETE CASCADE,
    FOREIGN KEY (id_church) REFERENCES churches(id) ON DELETE CASCADE,
    FOREIGN KEY (id_ministry) REFERENCES ministry(id) ON DELETE CASCADE,
    FOREIGN KEY (id_instrument) REFERENCES instrument(id) ON DELETE CASCADE,
    FOREIGN KEY (id_status) REFERENCES status(id) ON DELETE CASCADE
);

CREATE TABLE churches (
    id CHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE ministry (
    id CHAR(36) NOT NULL PRIMARY KEY,
    value VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE category (
    id CHAR(36) NOT NULL PRIMARY KEY,
    value VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE instrument (
    id CHAR(36) NOT NULL PRIMARY KEY,
    id_category CHAR(36) NOT NULL,
    value VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_category) REFERENCES category(id) ON DELETE CASCADE
);

CREATE TABLE status (
    id CHAR(36) NOT NULL PRIMARY KEY,
    value VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
