CREATE TABLE users(
    id CHAR(36) NOT NULL DEFAULT(UUID()) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_id CHAR(36) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(password_id) REFERENCES password(id) ON DELETE CASCADE
);

CREATE TABLE password(
    id CHAR(36) NOT NULL DEFAULT(UUID()) PRIMARY KEY,
    password_hash VARCHAR(255) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE salt(
    id CHAR(36) NOT NULL DEFAULT(UUID()) PRIMARY KEY,
    salt VARCHAR(255) NOT NULL,
    password_id CHAR(36) NOT NULL,
    expired TIMESTAMP,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(password_id) REFERENCES password(id) ON DELETE CASCADE
);

CREATE TABLE user_profile(
	id CHAR(36) NOT NULL DEFAULT (UUID()) PRIMARY KEY,
    id_user CHAR(36) NOT NULL,
    id_church CHAR(36) NOT NULL,
    id_ministry VARCHAR(100) NOT NULL,
	instrument VARCHAR(255) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (id_church) REFERENCES churches(id) ON DELETE CASCADE,
	FOREIGN KEY (id_ministry) REFERENCES ministry(id) ON DELETE CASCADE
);

CREATE TABLE churches(
	id CHAR(36) NOT NULL DEFAULT (UUID()) PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
	create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE instrument();
